import tensorflow as tf

class Unet_default(tf.keras.Model):
    def __init__(self, input_shape, kernel_size=3, filters=32, dropout_frac=0.1, filter_increase_factor=1):
        super(Unet_default, self).__init__()
        self.c1_1 = tf.keras.layers.Conv2D(int(filters*(1*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same', input_shape=input_shape)
        self.act1_1 = tf.keras.layers.Activation('relu')
        self.bn1_1 = tf.keras.layers.BatchNormalization()
        self.c1_2 = tf.keras.layers.Conv2D(int(filters*(1*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act1_2 = tf.keras.layers.Activation('relu')
        self.bn1_2 = tf.keras.layers.BatchNormalization()
        self.mp1 = tf.keras.layers.MaxPool2D()
        self.do1 = tf.keras.layers.Dropout(dropout_frac)

        self.c2_1 = tf.keras.layers.Conv2D(int(filters*(2*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act2_1 = tf.keras.layers.Activation('relu')
        self.bn2_1 = tf.keras.layers.BatchNormalization()
        self.c2_2 = tf.keras.layers.Conv2D(int(filters*(2*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act2_2 = tf.keras.layers.Activation('relu')
        self.bn2_2 = tf.keras.layers.BatchNormalization()
        self.mp2 = tf.keras.layers.MaxPool2D()
        self.do2 = tf.keras.layers.Dropout(dropout_frac)

        self.c3_1 = tf.keras.layers.Conv2D(int(filters*(4*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act3_1 = tf.keras.layers.Activation('relu')
        self.bn3_1 = tf.keras.layers.BatchNormalization()
        self.c3_2 = tf.keras.layers.Conv2D(int(filters*(4*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act3_2 = tf.keras.layers.Activation('relu')
        self.bn3_2 = tf.keras.layers.BatchNormalization()
        self.mp3 = tf.keras.layers.MaxPool2D()
        self.do3 = tf.keras.layers.Dropout(dropout_frac)

        self.c4_1 = tf.keras.layers.Conv2D(int(filters*(8*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act4_1 = tf.keras.layers.Activation('relu')
        self.bn4_1 = tf.keras.layers.BatchNormalization()
        self.c4_2 = tf.keras.layers.Conv2D(int(filters*(8*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act4_2 = tf.keras.layers.Activation('relu')
        self.bn4_2 = tf.keras.layers.BatchNormalization()
        self.mp4 = tf.keras.layers.MaxPool2D()
        self.do4 = tf.keras.layers.Dropout(dropout_frac)

        self.c5_1 = tf.keras.layers.Conv2D(int(filters*(16*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act5_1 = tf.keras.layers.Activation('relu')
        self.bn5_1 = tf.keras.layers.BatchNormalization()
        self.c5_2 = tf.keras.layers.Conv2D(int(filters*(16*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act5_2 = tf.keras.layers.Activation('relu')
        self.bn5_2 = tf.keras.layers.BatchNormalization()

        self.tc6_1 = tf.keras.layers.Conv2DTranspose(int(filters*(8*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same', strides=(2,2))
        self.act6_1 = tf.keras.layers.Activation('relu')
        self.bn6_1 = tf.keras.layers.BatchNormalization()
        self.do6 = tf.keras.layers.Dropout(dropout_frac)
        self.c6_2 = tf.keras.layers.Conv2D(int(filters*(8*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act6_2 = tf.keras.layers.Activation('relu')
        self.bn6_2 = tf.keras.layers.BatchNormalization()
        self.c6_3 = tf.keras.layers.Conv2D(int(filters*(8*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act6_3 = tf.keras.layers.Activation('relu')
        self.bn6_3 = tf.keras.layers.BatchNormalization()

        self.tc7_1 = tf.keras.layers.Conv2DTranspose(int(filters*(4*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same', strides=(2,2))
        self.act7_1 = tf.keras.layers.Activation('relu')
        self.bn7_1 = tf.keras.layers.BatchNormalization()
        self.do7 = tf.keras.layers.Dropout(dropout_frac)
        self.c7_2 = tf.keras.layers.Conv2D(int(filters*(4*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act7_2 = tf.keras.layers.Activation('relu')
        self.bn7_2 = tf.keras.layers.BatchNormalization()
        self.c7_3 = tf.keras.layers.Conv2D(int(filters*(4*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act7_3 = tf.keras.layers.Activation('relu')
        self.bn7_3 = tf.keras.layers.BatchNormalization()

        self.tc8_1 = tf.keras.layers.Conv2DTranspose(int(filters*(2*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same', strides=(2,2))
        self.act8_1 = tf.keras.layers.Activation('relu')
        self.bn8_1 = tf.keras.layers.BatchNormalization()
        self.do8 = tf.keras.layers.Dropout(dropout_frac)
        self.c8_2 = tf.keras.layers.Conv2D(int(filters*(2*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act8_2 = tf.keras.layers.Activation('relu')
        self.bn8_2 = tf.keras.layers.BatchNormalization()
        self.c8_3 = tf.keras.layers.Conv2D(int(filters*(2*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act8_3 = tf.keras.layers.Activation('relu')
        self.bn8_3 = tf.keras.layers.BatchNormalization()

        self.tc9_1 = tf.keras.layers.Conv2DTranspose(int(filters*(1*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same', strides=(2,2))
        self.act9_1 = tf.keras.layers.Activation('relu')
        self.bn9_1 = tf.keras.layers.BatchNormalization()
        self.do9 = tf.keras.layers.Dropout(dropout_frac)
        self.c9_2 = tf.keras.layers.Conv2D(int(filters*(1*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act9_2 = tf.keras.layers.Activation('relu')
        self.bn9_2 = tf.keras.layers.BatchNormalization()
        self.c9_3 = tf.keras.layers.Conv2D(int(filters*(1*filter_increase_factor)), kernel_size, kernel_initializer='he_normal', padding='same')
        self.act9_3 = tf.keras.layers.Activation('relu')
        self.bn9_3 = tf.keras.layers.BatchNormalization()

        self.prob_mask = tf.keras.layers.Conv2D(1, (1,1), activation='sigmoid')

    def call(self, inputs, training: bool):
        x = self.c1_1(inputs)
        x = self.act1_1(x)
        x = self.bn1_1(x, training=training)
        x = self.c1_2(x)
        x = self.act1_2(x)
        c1 = self.bn1_2(x, training=training)
        x = self.mp1(c1)
        x = self.do1(x, training=training)

        x = self.c2_1(x)
        x = self.act2_1(x)
        x = self.bn2_1(x, training=training)
        x = self.c2_2(x)
        x = self.act2_2(x)
        c2 = self.bn2_2(x, training=training)
        x = self.mp2(c2)
        x = self.do2(x, training=training)

        x = self.c3_1(x)
        x = self.act3_1(x)
        x = self.bn3_1(x, training=training)
        x = self.c3_2(x)
        x = self.act3_2(x)
        c3 = self.bn3_2(x, training=training)
        x = self.mp3(c3)
        x = self.do3(x, training=training)

        x = self.c4_1(x)
        x = self.act4_1(x)
        x = self.bn4_1(x, training=training)
        x = self.c4_2(x)
        x = self.act4_2(x)
        c4 = self.bn4_2(x, training=training)
        x = self.mp4(x)
        x = self.do4(x, training=training)

        x = self.c5_1(x)
        x = self.act5_1(x)
        x = self.bn5_1(x, training=training)
        x = self.c5_2(x)
        x = self.act5_2(x)
        x = self.bn5_2(x, training=training)

        x = self.tc6_1(x)
        x = self.act6_1(x)
        x = self.bn6_1(x, training=training)
        x = tf.keras.layers.Concatenate()([c4,x])
        x = self.do6(x, training=training)
        x = self.c6_2(x)
        x = self.act6_2(x)
        x = self.bn6_2(x, training=training)
        x = self.c6_3(x)
        x = self.act6_3(x)
        x = self.bn6_3(x, training=training)

        x = self.tc7_1(x)
        x = self.act7_1(x)
        x = self.bn7_1(x, training=training)
        x = tf.keras.layers.Concatenate()([c3,x])
        x = self.do7(x, training=training)
        x = self.c7_2(x)
        x = self.act7_2(x)
        x = self.bn7_2(x, training=training)
        x = self.c7_3(x)
        x = self.act7_3(x)
        x = self.bn7_3(x, training=training)

        x = self.tc8_1(x)
        x = self.act8_1(x)
        x = self.bn8_1(x, training=training)
        x = tf.keras.layers.Concatenate()([c2,x])
        x = self.do8(x, training=training)
        x = self.c8_2(x)
        x = self.act8_2(x)
        x = self.bn8_2(x, training=training)
        x = self.c8_3(x)
        x = self.act8_3(x)
        x = self.bn8_3(x, training=training)
    
        x = self.tc9_1(x)
        x = self.act9_1(x)
        x = self.bn9_1(x, training=training)
        x = tf.keras.layers.Concatenate()([c1,x])
        x = self.do9(x, training=training)
        x = self.c9_2(x)
        x = self.act9_2(x)
        x = self.bn9_2(x, training=training)
        x = self.c9_3(x)
        x = self.act9_3(x)
        x = self.bn9_3(x, training=training)

        return self.prob_mask(x)